name: classinsights
description: Multiplatform Application for School Data Visualization
publish_to: "none"
repository: "https://github.com/ClassInsights/App"
issue_tracker: "https://github.com/ClassInsights/App/issues"
documentation: "https://github.com/ClassInsights/App/blob/main/README.md"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.13
  package_info_plus: ^4.1.0
  flutter_web_auth_2: ^2.2.1
  web_socket_channel: ^2.4.0
  syncfusion_flutter_charts: ^22.2.12
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  dart_jsonwebtoken: ^2.11.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/icon.png
